# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cst495-Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cst495-Project
  pod 'Parse'
  pod 'ParseUI'

  target 'Cst495-ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cst495-ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
